frappe.query_reports["Customer Item Gap"] = {
  filters: [
    {
      fieldname: "company",
      label: __("Company"),
      fieldtype: "Link",
      options: "Company",
      reqd: 1,
      default: frappe.defaults.get_user_default("Company"),
    },
    {
      fieldname: "from_date",
      label: __("From Date"),
      fieldtype: "Date",
      reqd: 1,
      default: frappe.datetime.add_months(frappe.datetime.get_today(), -3),
    },
    {
      fieldname: "to_date",
      label: __("To Date"),
      fieldtype: "Date",
      reqd: 1,
      default: frappe.datetime.get_today(),
    },
    {
      fieldname: "item_code",
      label: __("Item Code"),
      fieldtype: "Link",
      options: "Item",
      reqd: 1,
    },
    {
      fieldname: "territory",
      label: __("Territory"),
      fieldtype: "Link",
      options: "Territory",
    },
    {
      fieldname: "city",
      label: __("City"),
      fieldtype: "Data",
    },
    {
      fieldname: "state",
      label: __("State"),
      fieldtype: "Data",
    },
    {
      fieldname: "customer_group",
      label: __("Customer Group"),
      fieldtype: "Link",
      options: "Customer Group",
    },
    {
      fieldname: "sales_person",
      label: __("Sales Person"),
      fieldtype: "Link",
      options: "Sales Person",
    },
    {
      fieldname: "dropped_lookback_months",
      label: __("Dropped Lookback"),
      fieldtype: "Select",
      options: [
        { value: "1", label: __("Last 1 Month") },
        { value: "2", label: __("Last 2 Months") },
        { value: "3", label: __("Last 3 Months") },
        { value: "6", label: __("Last 6 Months") },
        { value: "9", label: __("Last 9 Months") },
        { value: "12", label: __("Last 1 Year") },
      ],
      default: "12",
    },
    {
      fieldname: "active_customers_only",
      label: __("Active Customers Only"),
      fieldtype: "Check",
      default: 1,
    },
    {
      fieldname: "buyers_only",
      label: __("Buyers Only"),
      fieldtype: "Check",
      default: 0,
    },
    {
      fieldname: "opportunities_only",
      label: __("Opportunities Only"),
      fieldtype: "Check",
      default: 0,
    },
  ],
};
